services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ywc20
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ywc20
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
